CREATE TABLE IF NOT EXISTS "schema_migrations" ("version" INTEGER PRIMARY KEY, "inserted_at" TEXT);
CREATE TABLE IF NOT EXISTS "blackboards" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "current_claim" TEXT NOT NULL, "support_strength" NUMERIC NOT NULL, "active_objection" TEXT, "analogy_of_record" TEXT, "frontier_pool" JSON, "cemetery" JSON, "cycle_count" INTEGER DEFAULT 0, "embedding" BLOB, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL, "translator_frameworks_used" TEXT DEFAULT ('[]'));
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "blackboard_snapshots" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "blackboard_id" INTEGER NOT NULL CONSTRAINT "blackboard_snapshots_blackboard_id_fkey" REFERENCES "blackboards"("id") ON DELETE CASCADE, "cycle_number" INTEGER NOT NULL, "state_json" JSON, "embedding_vector" BLOB, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE INDEX "blackboard_snapshots_blackboard_id_cycle_number_index" ON "blackboard_snapshots" ("blackboard_id", "cycle_number");
CREATE TABLE IF NOT EXISTS "agent_contributions" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "blackboard_id" INTEGER NOT NULL CONSTRAINT "agent_contributions_blackboard_id_fkey" REFERENCES "blackboards"("id") ON DELETE CASCADE, "cycle_number" INTEGER NOT NULL, "agent_role" TEXT NOT NULL, "model_used" TEXT NOT NULL, "input_prompt" TEXT NOT NULL, "output_text" TEXT NOT NULL, "accepted" INTEGER DEFAULT false NOT NULL, "support_delta" NUMERIC, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE INDEX "agent_contributions_blackboard_id_cycle_number_agent_role_index" ON "agent_contributions" ("blackboard_id", "cycle_number", "agent_role");
CREATE TABLE IF NOT EXISTS "cemetery_entries" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "blackboard_id" INTEGER NOT NULL CONSTRAINT "cemetery_entries_blackboard_id_fkey" REFERENCES "blackboards"("id") ON DELETE CASCADE, "claim" TEXT NOT NULL, "cause_of_death" TEXT NOT NULL, "final_support" NUMERIC NOT NULL, "cycle_killed" INTEGER NOT NULL, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE INDEX "cemetery_entries_blackboard_id_cycle_killed_index" ON "cemetery_entries" ("blackboard_id", "cycle_killed");
CREATE TABLE IF NOT EXISTS "frontier_ideas" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "blackboard_id" INTEGER NOT NULL CONSTRAINT "frontier_ideas_blackboard_id_fkey" REFERENCES "blackboards"("id") ON DELETE CASCADE, "idea_text" TEXT NOT NULL, "sponsor_count" INTEGER DEFAULT 0 NOT NULL, "cycles_alive" INTEGER DEFAULT 0 NOT NULL, "activated" INTEGER DEFAULT false NOT NULL, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE INDEX "frontier_ideas_blackboard_id_activated_index" ON "frontier_ideas" ("blackboard_id", "activated");
CREATE INDEX "frontier_ideas_blackboard_id_sponsor_count_index" ON "frontier_ideas" ("blackboard_id", "sponsor_count");
CREATE TABLE IF NOT EXISTS "trajectory_points" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "blackboard_id" INTEGER NOT NULL CONSTRAINT "trajectory_points_blackboard_id_fkey" REFERENCES "blackboards"("id") ON DELETE CASCADE, "cycle_number" INTEGER NOT NULL, "embedding_vector" BLOB NOT NULL, "claim_text" TEXT NOT NULL, "support_strength" NUMERIC NOT NULL, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE INDEX "trajectory_points_blackboard_id_cycle_number_index" ON "trajectory_points" ("blackboard_id", "cycle_number");
INSERT INTO schema_migrations VALUES(20260131233831,'2026-01-31T23:39:05');
INSERT INTO schema_migrations VALUES(20260131234851,'2026-01-31T23:49:37');
INSERT INTO schema_migrations VALUES(20260131235421,'2026-01-31T23:54:41');
INSERT INTO schema_migrations VALUES(20260201000629,'2026-02-01T00:07:40');
INSERT INTO schema_migrations VALUES(20260201001119,'2026-02-01T00:11:44');
INSERT INTO schema_migrations VALUES(20260201001434,'2026-02-01T00:16:16');
INSERT INTO schema_migrations VALUES(20260201102817,'2026-02-01T10:35:54');
